/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_2 (
    input clk,
    input rst,
    input [6:0] player1Posx,
    input [6:0] player1Posy,
    input [6:0] player2Posx,
    input [6:0] player2Posy,
    input [27:0] player1Projx,
    input [27:0] player1Projy,
    input [27:0] player2Projx,
    input [27:0] player2Projy,
    input [48:0] obstacle,
    output reg [1175:0] mapArr
  );
  
  
  
  localparam COLOR_BLACK = 24'h000000;
  
  localparam COLOR_P1 = 24'h00ff00;
  
  reg [1175:0] mapTemp;
  
  localparam COLOR_P2 = 24'h0000ff;
  
  localparam COLOR_PROJ = 24'h00ffff;
  
  localparam COLOR_OBSTACLE = 24'hff0000;
  
  integer x;
  integer y;
  integer pr;
  
  always @* begin
    for (x = 1'h0; x < 3'h7; x = x + 1) begin
      for (y = 1'h0; y < 3'h7; y = y + 1) begin
        mapTemp[(x)*168+(y)*24+23-:24] = 24'h000000;
        if (player1Posx == 1'h1 << x && player1Posy == 1'h1 << y) begin
          mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ff00;
        end else begin
          if (player2Posx == 1'h1 << x && player2Posy == 1'h1 << y) begin
            mapTemp[(x)*168+(y)*24+23-:24] = 24'h0000ff;
          end else begin
            if (obstacle[(x)*7+(y)*1+0-:1] == 1'h1) begin
              mapTemp[(x)*168+(y)*24+23-:24] = 24'hff0000;
            end else begin
              if (player1Projx[0+6-:7] == (1'h1 << x) && player1Projy[0+6-:7] == (1'h1 << y)) begin
                mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
              end else begin
                if (player1Projx[7+6-:7] == (1'h1 << x) && player1Projy[7+6-:7] == (1'h1 << y)) begin
                  mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                end else begin
                  if (player1Projx[14+6-:7] == (1'h1 << x) && player1Projy[14+6-:7] == (1'h1 << y)) begin
                    mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                  end else begin
                    if (player1Projx[21+6-:7] == (1'h1 << x) && player1Projy[21+6-:7] == (1'h1 << y)) begin
                      mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                    end else begin
                      if (player2Projx[0+6-:7] == (1'h1 << x) && player2Projy[0+6-:7] == (1'h1 << y)) begin
                        mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                      end else begin
                        if (player2Projx[7+6-:7] == (1'h1 << x) && player2Projy[7+6-:7] == (1'h1 << y)) begin
                          mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                        end else begin
                          if (player2Projx[14+6-:7] == (1'h1 << x) && player2Projy[14+6-:7] == (1'h1 << y)) begin
                            mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                          end else begin
                            if (player2Projx[21+6-:7] == (1'h1 << x) && player2Projy[21+6-:7] == (1'h1 << y)) begin
                              mapTemp[(x)*168+(y)*24+23-:24] = 24'h00ffff;
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    mapArr = mapTemp;
  end
endmodule
