/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module obstacles_8 (
    input clk,
    input rst,
    output reg [48:0] obstacle
  );
  
  
  
  always @* begin
    obstacle[42+6-:7] = 7'h00;
    obstacle[35+6-:7] = 7'h14;
    obstacle[28+6-:7] = 7'h00;
    obstacle[21+6-:7] = 7'h08;
    obstacle[14+6-:7] = 7'h00;
    obstacle[7+6-:7] = 7'h14;
    obstacle[0+6-:7] = 7'h00;
  end
endmodule
