/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module digit_lut_18 (
    input [6:0] value,
    output reg [2:0] dec
  );
  
  
  
  always @* begin
    
    case (value)
      7'h00: begin
        dec = 3'h7;
      end
      7'h01: begin
        dec = 3'h0;
      end
      7'h02: begin
        dec = 3'h1;
      end
      7'h04: begin
        dec = 3'h2;
      end
      7'h08: begin
        dec = 3'h3;
      end
      7'h10: begin
        dec = 3'h4;
      end
      7'h20: begin
        dec = 3'h5;
      end
      7'h40: begin
        dec = 3'h6;
      end
      default: begin
        dec = 3'h0;
      end
    endcase
  end
endmodule
